cleaning up a bit

diff --git a/sample-workflow-action.yml b/sample-workflow-action.yml
--- a/sample-workflow-action.yml
+++ b/sample-workflow-action.yml
@@ -15,4 +15,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Run Ansible Playbook
-        run: ansible-playbook -i ./ansible/hosts ./ansible/hello_playbook.yml -vvvv --limit=operations3.access-ci.org
+        working-directory: ./ansible
+        run: |
+          ansible-playbook -i hosts hello_playbook.yml -vvvv --limit=operations3.access-ci.org \
+            || { echo "Ansible playbook failed"; exit 1; }
